<a href="https://colab.research.google.com/github/RomaViraj/APT/blob/master/AT_Lesson_32_Reference_v0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 32: Python Dictionary Operations II

**WARNING:** The reference notebook is meant **ONLY** for a teacher. Please **DO NOT** share it with any student. 

The contents of the reference notebook are meant only to prepare a teacher for a class. To conduct the class, use the class copy of the reference notebook. The link and the instructions for the same are provided in the **Notes To The Teacher** section.


|Particulars|Description|
|-|-|
|**Topic**|Python Dictionary Operations II|
|||
|**Class Description**|In this class, a student will learn to apply more fundamental and advanced operations on a Python dictionary|
|||
|**Class**|C32|
|||
|**Class Time**|45 minutes|
|||
|**Goal**|Add a new item to a dictionary|
||Create a Python dictionary from two Python list|
||Remove an item from a dictionary|
||Update an existing item in a dictionary|
||Check whether an item exists in a dictionary|
|||
|**Teacher Resources**|Google Account|
||Link to Lesson 32 Colab reference notebook|
||Laptop with internet connectivity|
||Earphones with mic|
|||
|**Student Resources**|Google Account|
||Laptop with internet connectivity|
||Earphones with mic|

---

### Class Structure

A class is divided into three parts, as shown in the table below.

|Parts|Duration|
|-|-|
|**Warm-Up**|5 minutes|
|||
|**Teacher-Student Activities**|35 minutes|
|||
|**Wrap-Up**|5 minutes|

---

### Notes To The Teacher

Before beginning the class:

1. Open the **AT - Lesson 32 - Class Copy - v0** file by clicking on the link provided in the **Activities** section under the title **Python Dictionary Operations II (Class Copy)**.  

2. After opening the file mentioned in the first point, create its duplicate copy by following the steps described below:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=400>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

    - In the duplicate copy, click on the **Share** button on the top right corner of the notebook. A new dialogue box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/2_share_button.png' width=500>

    - Click on the tiny downward arrow next to **Anyone with the link can view** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/3_anyone_can_view.png' width=500>

    - Click on the **More...** option. A new page on the dialogue box will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/4_more_option.png' width=500>

    - Click on the circle next to **On - Anyone with the link** option. Now, go down and click on the tiny downward box next to **Can edit** text. A drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/5_anyone_with_the_link.png' width=500>

    - Click on the **Can edit** option. Then click on the **Save** button. You will be directed back to the first page of the dialogue box.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/6_can_edit.png' width=500>

    - Make sure that under the **Link sharing on** section, **Anyone with the link can edit** option is selected. 

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/7_anyone_can_edit.png' width=500>

    - Then click on the **Done** button.

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Lesson32** format. 


4. Now, finish the **Warm-Up** section. Afterwards, proceed with the class using the duplicate copy of the notebook. You can share the link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Lesson32**) with the student through the chat window.

5. When a student executes the code for the first time in the duplicate copy that you shared with them, they may get the following warning:

   ```
    Warning: This notebook was not authored by Google. This notebook was 
    authored by xyz@gmail.com. It may request access to your data stored 
    with Google such as files, emails and contacts. Please review the source 
    code and contact the creator of this notebook at xyz@gmail.com with any 
    additional questions. 

                                                      Cancel. Run Anyway.
  ```

6. Ask the student to click on the `Run Anyway` button.

7. Wherever you see the hat (**^**) sign on the heading of activity, give a hats-off to the student at the end of the activity.

    - Single hat sign, i.e., **^** denotes give hats-off for concentration. You have to assess the concentration level of a student based on their attentiveness and understanding of the concept.

    - Double hat signs, i.e., **^^** denotes give hats-off for creativity. It can be an alternative approach to writing a code for an activity or applying the logic in a totally different problem statement.

    - Triple hat signs, i.e., **^^^** denotes give hats-off for persistence. It is the ability of a student to not give up on writing code and writing code with minimal teacher support.

8. Every time you execute your code in the Google Colab notebook, please don't forget to save it by pressing the **Ctrl + S** keys (or **Command + S** keys if you are using a Mac). While saving the notebook, you or student may encounter the following error:

   ```
    Save failed
    
    The notebook has been changed outside of this session. Would you like to 
    overwrite existing changes?
    
                                                              CANCEL    YES
   ```

   Click on the `YES` button.

9. Occasionally, you may encounter some error such as `NameError, ReferenceError, ImportError` or `ModuleNotFoundError` after executing the code in $k^{th}$ code cell (where $k > 0$). Most likely, due to poor internet speed, the Colab notebook might have lost the information that all the previous codes have been executed already. As a remedy, run codes in the code cells beginning from the first code cell till the $(k - 1)^{th}$ code cell. For e.g., if the code in the $5^{th}$ code cell fails to run because of one of the aforementioned errors, execute the codes in all the first four code cells again.

10. For every **Teacher Action**, the teacher is supposed to share their screen with the student. Similarly, for every **Student Action**, the student is supposed to share their screen with the teacher.


---

### Warm-Up

```
TEACHER
  Hi student_name! How are you doing?

EXPECTED STUDENT RESPONSE
  I am doing good, teacher. How about you?


TEACHER
  I am having a good time, thank you. So, how was your day? What did you do 
  today?

EXPECTED STUDENT RESPONSE 
  I went to school. Had my lunch. Played a game and then did my homework 
  before this class.


TEACHER
  That's great. I am glad that you are having a good day. Now, let's do a 
  quick recap of our previous class. Can you recall the concepts you 
  learnt in the previous lesson?

EXPECTED STUDENT RESPONSE
  We learnt how to calculate the length of a dictionary and how to retrieve 
  items from a dictionary.

TEACHER
  Excellent! You recalled everything that you learnt in the last class. 
  Great job! Keep it up. 
  I have an exciting quiz question for you! Are you ready to answer this question?    
  ```   
  **Instructions for the Teacher:**
  -  Please click on the "Quiz Time" button on the bottom right corner of your screen to start the In-Class Quiz.<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/quiz-time.png' width=100>   
  - A quiz will be visible to both you and the student. Encourage the student to answer the quiz question. 
  - The student may choose the wrong option, help the student to think correctly about the question and then answer again. 
  - After the student selects the correct option, the "End Quiz" button will start appearing on your screen.  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/end-quiz.png' width=100>  
  - Click the "End quiz" to close the quiz pop-up and continue the class. 
  - Do not spend more than 2 minutes on this quiz.

```
TEACHER
  In this class, we are going to learn how to 
  apply more fundamental and advanced operations on a Python dictionary.

  So, are you excited for this class?

EXPECTED STUDENT RESPONSE
  Yes, teacher.


TEACHER
  All right. Let's get started. I'm sharing the link to the Colab notebook 
  for this class with you. Open it up.

  Note:
    - Share the duplicate copy of the notebook that you just created with 
      the student through the chat window.
    
EXPECTED STUDENT RESPONSE
  The student opens the Colab notebook.
```

---

### Teacher-Student Activities

Let's continue the discussion on Python dictionaries. In this class, we will learn how to:

- Add a new item to a dictionary

- Create a Python dictionary from two Python list

- Remove an item from a dictionary

- Update an existing item in a dictionary

- How to check whether an item exists in a dictionary

- And few important points about a Python dictionary

Let's quickly create the `my_dict` dictionary again and continue this class from the **Activity 1: Adding New Item** section.

---

#### Recap

**A python dictionary is a collection of key-value pairs.** 

|Key         |Value                  |
|------------|-----------------------|
|Front Camera|16 MP                  |
|Battery     |3300 mAh               |
|Processor   |Qualcomm Snapdragon 845|
|Display     |6.28 inches            |
|RAM         |6 GB                   |
|Rear Camera |16 MP + 20 MP          |
|Price (INR) |28990                  |
|Fast Charge |True                   |

Collectively, both a key and its corresponding value constitute an item stored in a dictionary. 

A dictionary is created using curly brackets (`{}`). A key and its corresponding value are mapped using the colon (`:`) sign and each key-value pair is separated by a comma. 

In [ ]:
# Create a dictionary as a collection of key-value pairs containing the items shown in the table above.
my_dict = {'Front Camera' : '16 MP', # First key-value pair 
           'Battery' : '3300 mAh', # Second key-value pair
           'Processor' : 'Qualcomm Snapdragon 845', # Third key-value pair
           'Display' : '6.28 inches', # Fourth key-value pair
           'RAM' : '6 GB', # Fifth key-value pair
           'Rear Camera' : '16 MP + 20 MP', # Sixth key-value pair
           'Price' : 28990, # Seventh key-value pair
           'Fast Charge' : True} # Eighth key-value pair

my_dict

{'Battery': '3300 mAh',
 'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Price': 28990,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

**Note** that the output will not always display the key-value pairs in the same order in which you entered the pairs in the dictionary.

---

#### Activity 1: Adding New Item

Let's also add the storage capacity of the smartphone to the `my_dict` dictionary. So the new item is `Memory` and the corresponding value is `'128 GB'`.

To add a new item to a dictionary, you simply have to use the square brackets as shown in the syntax below.

**Syntax:** `dictionary_name[key] = value`

where `dictionary_name` is some variable storing a dictionary.

In [ ]:
# Student Action: Add 'Memory' and '128 GB' as keys and values respectively to the 'my_dict' dictionary.
my_dict['Memory'] = '128 GB'
my_dict

{'Battery': '3300 mAh',
 'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Memory': '128 GB',
 'Price': 28990,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

As you can see, a new key-value pair, `'Memory' : '128 GB'` has been added to the `my_dict` dictionary.

---

#### Activity 2: The `zip()` Function

Sometimes you may require to create a dictionary from two Python lists. Consider the two lists shown below.

```
car_companies = ['Maruti Suzuki', 'Honda', 'Hyundai', 'Ford', 'Volkswagen']
car_models = [
                ['Baleno', 'Vitara Brezza', 'Ciaz'], 
                'City', 
                ['Verna', 'Creta'], 
                ['Figo', 'EcoSport', 'Aspire'], 
                ['Polo', 'Tiguan', 'Vento']
              ]
```

The `car_companies` list contains the name of the car manufacturers. The `car_models` list contains the models of cars manufactured by them.

Let's create a dictionary which maps every car model to its corresponding manufacturer. Let's store it in the `cars_dict`.

To create a dictionary from two lists, use the `zip()` and `dict()` function using the following syntax.

**Syntax:** `dictionary_name = dict(zip(list1, list2))`

where the `zip()` function joins the lists `list1` and `list2` but the `dict()` function converts the resulting object into a dictionary.

In [ ]:
# Student Action: Create a new dictionary by joining the 'car_companies' & 'car_models' lists. Store it in the 'cars_dict' variable.
car_companies = ['Maruti Suzuki', 'Honda', 'Hyundai', 'Ford', 'Volkswagen']
car_models = [['Baleno', 'Vitara Brezza', 'Ciaz'], 
              'City', 
              ['Verna', 'Creta'], 
              ['Figo', 'EcoSport', 'Aspire'], 
              ['Polo', 'Tiguan', 'Vento']]

cars_dict = dict(zip(car_companies, car_models))
cars_dict

{'Ford': ['Figo', 'EcoSport', 'Aspire'],
 'Honda': 'City',
 'Hyundai': ['Verna', 'Creta'],
 'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
 'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

As you can see, a new dictionary called `cars_dict` has been created using the `zip()` and `dict()` functions. 

The `zip()` function maps items of the first list with the items of the second list such that former become **keys** and latter become the corresponding **values** of the keys.

**Note** that the first item contained in the first list becomes **key** for the first item in the second list and the second item in the first list becomes **key** for the second item in the second list and so on.

Instead of using the `dict()` function, if you use the `list()` function on top of the `zip()` function, you will get a Python list containing the items of the two lists as a collection of key-value pairs in tuples. 


In [ ]:
# Student Action: Create a new list by joining the 'car_companies' & 'car_models' lists. Store it in the 'cars_list' variable.
cars_list = list(zip(car_companies, car_models))
cars_list

[('Maruti Suzuki', ['Baleno', 'Vitara Brezza', 'Ciaz']),
 ('Honda', 'City'),
 ('Hyundai', ['Verna', 'Creta']),
 ('Ford', ['Figo', 'EcoSport', 'Aspire']),
 ('Volkswagen', ['Polo', 'Tiguan', 'Vento'])]

As you can see, the `zip()` function has clubbed the items of the `car_companies` and `car_models` as a key-value pair in a tuple and the `list()` function has created a list containing tuples.

---

#### Activity 3: List Comprehension For Dictionaries^^

You can also use the list comprehension method to create a Python dictionary.

Let's again map all the `car_models` items to the `car_companies` items by creating a new dictionary using the `zip()` function and the list comprehension method.

In [ ]:
# Teacher Action: Create a new dictionary using the list comprehension method to map all the 'car_models' items to the car_companies items.
new_cars_dict = {key : value for key, value in zip(car_companies, car_models)}
new_cars_dict

{'Ford': ['Figo', 'EcoSport', 'Aspire'],
 'Honda': 'City',
 'Hyundai': ['Verna', 'Creta'],
 'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
 'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

The above list comprehension should be read as "*For every key & value in the object returned by the `zip()` function, add them to the dictionary*". To add the key-value pair, you simply need to write `key` followed by the colon (`:`) sign, followed by `value`. 

**Syntax:** `{key : value for key, value in zip(list1, list2)}`

The variables `key` and `value` are dummy variables. You can use any variable in their places. 

E.g., `{x : y for x, y in zip(list1, list2)}, {p : q for p, q in zip(list1, list2)}` etc.

In [ ]:
# Student Action: Run the code below.
new_cars_dict1 = {x : y for x, y in zip(car_companies, car_models)}
new_cars_dict1

{'Ford': ['Figo', 'EcoSport', 'Aspire'],
 'Honda': 'City',
 'Hyundai': ['Verna', 'Creta'],
 'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
 'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

In [ ]:
# Student Action: Run the code below.
new_cars_dict2 = {p : q for p, q in zip(car_companies, car_models)}
new_cars_dict2

{'Ford': ['Figo', 'EcoSport', 'Aspire'],
 'Honda': 'City',
 'Hyundai': ['Verna', 'Creta'],
 'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
 'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

---

#### Activity 4: Removing Item From Dictionary

To remove an item from a dictionary, you can use the `pop()` function. Inside the `pop()` function, you have to provide the key for which the key-value pair must be removed from the dictionary.

Let's remove the item `'Battery' : '3300 mAh'` from the `my_dict` dictionary, using the `pop()` function.

In [ ]:
# Student Action: Remove the item 'Battery' : '3300 mAh' from the 'my_dict' dictionary.
my_dict.pop('Battery')
my_dict

{'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Memory': '128 GB',
 'Price': 28990,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

As you can see, the `pop()` function has removed `'Battery' : '3300 mAh'` item from the `my_dict` dictionary.

**Note:** The `pop()` function for a Python dictionary is different from the `pop()` function in Python list. In the case of dictionary, it takes the key of a key-value pair to remove the pair. 

**Syntax:** `python_dictionary.pop(key)`

There is another function called the `popitem()` to remove an item from a dictionary. However, it removes only the last item from a dictionary.

In [ ]:
# Student Action: Remove the last item from the dictionary.
print("The item remove by the popitem() function is", my_dict.popitem(), "\n")
my_dict

The item remove by the popitem() function is ('Memory', '128 GB') 



{'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Price': 28990,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

The item removed is returned as a key-value pair in a tuple.

---

#### Activity 5: Update Dictionary Item

Let's say the price of the smartphone, whose specifications are listed in the `my_dict` dictionary, changes to INR 25000. So, the `'Price': 28990` item in the `my_dict` dictionary must be updated.

To update an item in a dictionary, you need to enclose the key for that item in square brackets followed by the equals to sign, followed by the updated value as shown in the following syntax.

**Syntax:** `dictionary_name[key] = new_value` 

In [ ]:
# Student Action: Update the price of the smartphone in the 'my_dict' dictionary.
my_dict['Price'] = 25000
my_dict

{'Display': '6.28 inches',
 'Fast Charge': True,
 'Front Camera': '16 MP',
 'Price': 25000,
 'Processor': 'Qualcomm Snapdragon 845',
 'RAM': '6 GB',
 'Rear Camera': '16 MP + 20 MP'}

As you can see, the value corresponding to the `'Price'` is changed to `25000`.

---

#### Activity 6: The `in` & `not in` Keywords^^^

To check whether a key exists in a dictionary or not, you can use the `in` keyword. If a key exists in the dictionary, then the `in` keyword will return `True`, else it will return `False`. Similarly, if a key exists in the dictionary, then the `not in` keyword will return `False`, else it will return `True`.

You have already used them in `for` loops many times.

**Syntax:** `key in dictionary_name`

**Syntax:** `key not in dictionary_name`

Let's find out whether the keys, `'Honda'` and `'Audi'` exist in the `cars_dict` or not.

In [ ]:
# Student Action: Check whether the item 'Honda' exists in the 'cars_dict' dictionary using the 'in' keyword.
'Honda' in cars_dict

True

In [ ]:
# Student Action: Check whether the item 'Audi' exists in the 'cars_dict' dictionary using the 'in' keyword.
'Audi' not in cars_dict

True

---

#### Activity 7: The `update()` Function


The `update()` function is applied on a dictionary and it's input is another dictionary wherein both the dictionary may or may not contain the same keys. The `update()` function performs two operations:

1. It updates the existing key-value pair in a dictionary if a key exists. 

2. It adds the key-value pairs which do not exist in a dictionary.

Consider the two dictionaries:

```
cars_dict = {'Ford': ['Figo', 'EcoSport', 'Aspire'],
              'Honda': 'City',
              'Hyundai': ['Verna', 'Creta'],
              'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
              'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

supercars = {"Ford": "Mustang GT",
             "Lamborghini": ["Huracan", "Aventador", "Elemento"],
             "Koenigsegg": ["Agera", "Gemera", "Regera"],
             "Bugatti": "Veyron"}
```

When the `update()` function is applied on the `cars_dict` dictionary with the `supercars` dictionary as input, it updates the value of the `Ford` key and adds the other key-value pairs of the `supercars` dictionary to the `car_dict` dictionary.

In [ ]:
# Student Action: Create the 'supercars' dictionary and update the 'cars_dict' dictionary with the key-value pairs of the 'supercars' dictionary.
supercars = {"Ford": "Mustang GT",
             "Lamborghini": ["Huracan", "Aventador", "Elemento"],
             "Koenigsegg": ["Agera", "Gemera", "Regera"],
             "Bugatti": "Veyron"}
cars_dict.update(supercars)
cars_dict

{'Bugatti': 'Veyron',
 'Ford': 'Mustang GT',
 'Honda': 'City',
 'Hyundai': ['Verna', 'Creta'],
 'Koenigsegg': ['Agera', 'Gemera', 'Regera'],
 'Lamborghini': ['Huracan', 'Aventador', 'Elemento'],
 'Maruti Suzuki': ['Baleno', 'Vitara Brezza', 'Ciaz'],
 'Volkswagen': ['Polo', 'Tiguan', 'Vento']}

---

#### Activity 8: The `JSON` Objects^

JSON stands for **J**ava**S**cript **O**bject **N**otation. It is a way of storing data and exchanging it on the web across multiple servers. In fact, the information stored using JSON on a webpage of a website. 

- Go to any website. E.g., [IMDb](https://www.imdb.com/?ref_=nv_home)

- Right-click on an empty space. A list of action items will appear

- Click on the **View Page Source** option. The webpage will open in a new tab in HTML view.

- Hit *Commad + F* keys (on Mac) or *Ctrl + F* keys (on other) computers to initiate a search. Then in the search box type **json** and hit the return or enter key. You should be able to see **json** at least once in the searches.

A **JSON** object is much alike to a Python dictionary. The only difference being:

1. The boolean values in a JSON object are stored as `true` or `false`

2. The unavailable/missing values are stored as `null` whereas in Python (excluding Pandas or NumPy) they are stored as `None`.

Consider a sample `JSON` object below that is stored in a `movies_info` variable.

```
movies_info = """
{"hollywood":[
    {"year": 2014,
      "title": "X-Men: Days of Future Past",
      "info": {
        "directors": ["Bryan Singer"],
        "release_date": "2014-05-21T00:00:00Z",
        "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"],
        "rank": 9,
        "actors": ["Jennifer Lawrence", "Hugh Jackman", "Michael Fassbender"],
        "english": true
        }
    },
    {"year": 2014,
      "title": "Transformers: Age of Extinction",
      "info": {
        "directors": ["Michael Bay"],
        "release_date": "2014-06-25T00:00:00Z",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "rank": 10,
        "actors": ["Mark Wahlberg", "Nicola Peltz", "Jack Reynor"],
        "english": true
        }
    }
  ],
 "bollywood":[
    {"year": 2020,
      "title": "Angrezi Medium",
      "info": {
        "directors": ["Homi Adajania"],
        "release_date": "2030-03-13",
        "genres": ["Comdey", "Drama"],
        "rank": null,
        "actors": ["Irrfan Khan", "Radhika Madan", "Kareena Kapoor"],
        "english": false
        }
    }
  ]
}
"""
```

The above `JSON` object is essentially a Python dictionary having two key-value pairs wherein each key is a string containing a list as a value. The list further contains dictionaries whose keys are `year, title` and `info`. The `info` key further contains a dictionary having 6 key-value pairs.

Notice the values of the `english` keys. They are boolean values reported as `true` or `false`. The `rank` key holds numeric values for the first two occurrences and a `null` value for the last occurrence.

To load a `JSON` object as a Python dictionary you have to import the `json` module. Then use the `json.loads()` function whose input is a `json` object stored in a variable. 

**Note:** The above `json` object is stored as a string enclosed between three double quotes, i.e., (`""" """`). This is called a multiline string which you will learn in the upcoming classes.

At the moment, let's convert the above `JSON` object into a Python dictionary and check whether the boolean values are converted into Python booleans and the `null` value is converted into `None`.

In [ ]:
# Student Aciton: Convert the above JSON object into a Python dictionary.
import json

movies_info = """
{"hollywood":[
    {"year": 2014,
      "title": "X-Men: Days of Future Past",
      "info": {
        "directors": ["Bryan Singer"],
        "release_date": "2014-05-21T00:00:00Z",
        "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"],
        "rank": 9,
        "actors": ["Jennifer Lawrence", "Hugh Jackman", "Michael Fassbender"],
        "english": true
        }
    },
    {"year": 2014,
      "title": "Transformers: Age of Extinction",
      "info": {
        "directors": ["Michael Bay"],
        "release_date": "2014-06-25T00:00:00Z",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "rank": 10,
        "actors": ["Mark Wahlberg", "Nicola Peltz", "Jack Reynor"],
        "english": true
        }
    }
  ],
 "bollywood":[
    {"year": 2020,
      "title": "Angrezi Medium",
      "info": {
        "directors": ["Homi Adajania"],
        "release_date": "2030-03-13",
        "genres": ["Comdey", "Drama"],
        "rank": null,
        "actors": ["Irrfan Khan", "Radhika Madan", "Kareena Kapoor"],
        "english": false
        }
    }
  ]
}
"""

movies_dict = json.loads(movies_info)
movies_dict

{'bollywood': [{'info': {'actors': ['Irrfan Khan',
     'Radhika Madan',
     'Kareena Kapoor'],
    'directors': ['Homi Adajania'],
    'english': False,
    'genres': ['Comdey', 'Drama'],
    'rank': None,
    'release_date': '2030-03-13'},
   'title': 'Angrezi Medium',
   'year': 2020}],
 'hollywood': [{'info': {'actors': ['Jennifer Lawrence',
     'Hugh Jackman',
     'Michael Fassbender'],
    'directors': ['Bryan Singer'],
    'english': True,
    'genres': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
    'rank': 9,
    'release_date': '2014-05-21T00:00:00Z'},
   'title': 'X-Men: Days of Future Past',
   'year': 2014},
  {'info': {'actors': ['Mark Wahlberg', 'Nicola Peltz', 'Jack Reynor'],
    'directors': ['Michael Bay'],
    'english': True,
    'genres': ['Action', 'Adventure', 'Sci-Fi'],
    'rank': 10,
    'release_date': '2014-06-25T00:00:00Z'},
   'title': 'Transformers: Age of Extinction',
   'year': 2014}]}

In [ ]:
# Student Action: Verify whether the JSON object is converted into a Python dictionary or not.
type(movies_dict)

dict

---

#### Activity 9: The `clear()` Function

The `clear()` function simply clears or deletes all the key-values pairs from a dictionary.

In [ ]:
#### Student Action: Clear the contents of the 'movies_dict' dictionary.
movies_dict.clear()
movies_dict

{}

That's it! We have covered everything we need to about Python dictionaries. In the next class, we will learn about Python tuples.

**Note:** You can now attempt **Project 9**.

---

### Additional Activities

The activities starting from this point are optional. Please do these activities **ONLY** if you have time to spare in the class. Otherwise, skip to the **Wrap-Up** section. The additional activities will not be available in the class copy of the notebook. You will have to manually add these activities in the class copy by adding new text and code cells.

Moreover, you don't have to do all the additional activities. Depending on the availability of time in a class, you can choose the number of additional activities to perform from this collection. 

---

#### Activity 1: Exam Schedule

Create the following four dictionaries.

```
subject_1 = {'Name': 'Mathematics', 
             'Date': '28-04-2020', 
             'Day': 'Tuesday'}
subject_2 = {'Name': 'English Comm', 
             'Date': '29-04-2020', 
             'Day': 'Wednesday'}
subject_3 = {'Name': 'Science', 
             'Date': '30-04-2020', 
             'Day': 'Friday'}

my_time_table = {"Exam 1": subject_1, 
                 "Exam 2": subject_2, 
                 "Exam 3": subject_3}
```

Finally, print the contents of the `my_time_table` dictionary in the following format.

```
Exam 1
Name : Mathematics
Date : 28-04-2020
Day : Tuesday

Exam 2
Name : English Comm
Date : 29-04-2020
Day : Wednesday

Exam 3
Name : Science
Date : 30-04-2020
Day : Friday
```


In [ ]:
# Solution:
subject_1 = {'Name': 'Mathematics', 
             'Date': '28-04-2020', 
             'Day': 'Tuesday'}
subject_2 = {'Name': 'English Comm', 
             'Date': '29-04-2020', 
             'Day': 'Wednesday'}
subject_3 = {'Name': 'Science', 
             'Date': '30-04-2020', 
             'Day': 'Friday'}

my_time_table = {"Exam 1": subject_1, 
                 "Exam 2": subject_2, 
                 "Exam 3": subject_3}

for exam in my_time_table:
  print(exam)
  for d in my_time_table[exam]:
    print(d, ":", my_time_table[exam].get(d))
  print()

Exam 1
Name : Mathematics
Date : 28-04-2020
Day : Tuesday

Exam 2
Name : English Comm
Date : 29-04-2020
Day : Wednesday

Exam 3
Name : Science
Date : 30-04-2020
Day : Friday



---

#### Activity 2: Comprehension

Create a dictionary of cubes of the first 10 natural numbers using comprehension method.



In [ ]:
# Solution:
cubes_dict = {"cube of " + str(x) : x ** 3 for x in range(1, 11)}
cubes_dict

{'cube of 1': 1,
 'cube of 10': 1000,
 'cube of 2': 8,
 'cube of 3': 27,
 'cube of 4': 64,
 'cube of 5': 125,
 'cube of 6': 216,
 'cube of 7': 343,
 'cube of 8': 512,
 'cube of 9': 729}

---

#### Activity 3: List of Keys & Values

For the `my_dict` dictionary items, create separate Python lists for keys and values.

In [ ]:
# Solution:
py_keys_list = list(my_dict.keys())
py_values_list = list(my_dict.values())
print(py_keys_list)
print(py_values_list)

['Front Camera', 'Processor', 'Display', 'RAM', 'Rear Camera', 'Price', 'Fast Charge']
['16 MP', 'Qualcomm Snapdragon 845', '6.28 inches', '6 GB', '16 MP + 20 MP', 25000, True]


---

### Wrap-Up

```
TEACHER
  Did you enjoy the class?

EXPECTED STUDENT RESPONSE
  Yes, teacher.


TEACHER
  What part of the class did you enjoy?

EXPECTED STUDENT RESPONSE
  I enjoyed everything.


TEACHER
  I am glad you are having a good time. But make sure that you practice 
  writing code in your free time.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  In the next class, we will learn about Python tuples in detail.

EXPECTED STUDENT RESPONSE
  Sure teacher.


TEACHER
  See you in the next class. Bye!

EXPECTED STUDENT RESPONSE
  Bye teacher!
```

---

#### Activities

**Teacher Activities**

1. Python Dictionary Operations II (Class Copy)

   https://colab.research.google.com/drive/18ryA1Ivi8xtaTgW9SCvKg25uqJxSvjzL      

2. Python Dictionary Operations II (Reference)

   https://colab.research.google.com/drive/1RSb40q6av2a_HC3TY5-6WkAdltxEVyEb

---